[package]
name = "thermal_parser"
version = "0.0.1"
authors = ["Zach Zurn <zachzurn@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
barcoders = "1.0.2"
chardetng = "0.1.17"
encoding_rs = "0.8.33"
qr_code = "1.1.0"
